- name: Generar Reporte de Transacciones
        env:
          PGPASSWORD: tmiLSJC8dLiMrMh8
        run: |
          # Fíjate en el cambio del -U (Usuario)
          psql -h aws-0-us-west-2.pooler.supabase.com \
               -p 5432 \
               -U auditor_alertas.dodwsyjqvclcftfvklmr \
               -d postgres \
               -c "
          SELECT 
            CASE 
              WHEN fecha_registro > NOW() - INTERVAL '1 day' THEN 'REPORTE DIARIO'
              WHEN fecha_registro > NOW() - INTERVAL '7 days' THEN 'REPORTE SEMANAL'
              ELSE 'REPORTE MENSUAL'
            END as tipo_periodo,
            estado_transaccion,
            COUNT(*) as total_transacciones,
            SUM(monto_comision) as total_comisiones
          FROM silver.transacciones_servicios
          GROUP BY 1, 2;" > balance_servicios.txt
